server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

tmdb.api.key=${TMDB_API_KEY}
tmdb.api.base-url=https://api.themoviedb.org/3

cors.allowed.origins=${CORS_ORIGINS:http://localhost:5173}

spring.datasource.hikari.connection-init-sql=SET plan_cache_mode=force_custom_plan
spring.jpa.properties.hibernate.jdbc.use_get_generated_keys=true

logging.level.org.springframework.security=DEBUG
